[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[dev]
  command = "npm run start"
  targetPort = 3000
  publish = "dist"
  autoLaunch = true
  framework = "#custom"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/map/"
  to = "https://map.wecount.inclusivedesign.ca"
  status = 301

[[redirects]]
  from = "/admin/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}
